/*
two strings s and t
String t is generated by random shuffling string s 
and then add one more letter at a random position.

Return the letter that was added to t
*/
// String.fromCharCode(97) = 'a'
// str.charCodeAt('a') = 97 

// findTheDifference1(self, s: str, t: str) -> str:
//   rv = collections.Counter(t) - collections.Counter(s)
//   return "".join(rv.keys())

function comeLetter(s, t) {
  s = s.split("");
  t = t.split("");
  let countert = {};
  let counters = {};
  
  for (let i = 0; i < s.length; i++) {
    if (counters[s[i]]) {
      counters[s[i]]++;
    } else {
      counters[s[i]] = 1;
    }
  }
  
  for (let i = 0; i < t.length; i++) {
    if (countert[t[i]]) {
      countert[t[i]]++;
    } else {
      countert[t[i]] = 1;
    }
  }
  
  for (let obj in countert) {
    if (counters[obj]) {
      if (countert[obj] > counters[obj]) {
        return obj
      }
    } else {
      return obj
    }
  }
}